# Generated by Django 5.1.3 on 2024-12-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('continent', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
