# Generated by Django 5.1.3 on 2024-12-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superstar', '0004_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
