# Generated by Django 5.1.3 on 2024-12-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superstar', '0005_remove_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='state',
            name='population',
        ),
    ]
