# Generated by Django 5.1.3 on 2024-12-10 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstar', '0006_remove_state_capital_remove_state_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='superstar.state'),
        ),
    ]
