# Generated by Django 5.1.3 on 2024-12-10 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstar', '0008_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='superstar.city'),
        ),
    ]
