# Generated by Django 5.1.3 on 2024-12-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstar', '0009_alter_employee_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.CharField(max_length=10, unique=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='superstar.employee')),
            ],
        ),
    ]
